// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthTokens struct {
	AccessToken  *string   `json:"accessToken,omitempty"`
	RefreshToken *string   `json:"refreshToken,omitempty"`
	User         *AuthUser `json:"user"`
}

type AuthUser struct {
	ID        string  `json:"id"`
	FirstName string  `json:"firstName"`
	LastName  string  `json:"lastName"`
	Email     string  `json:"email"`
	Active    bool    `json:"active"`
	CreatedAt *string `json:"createdAt,omitempty"`
	UpdatedAt *string `json:"updatedAt,omitempty"`
	DeletedAt *string `json:"deletedAt,omitempty"`
}

type Category struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

type CreateCategoryInput struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

type CreateTagInput struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Page struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Slug        string  `json:"slug"`
	Status      string  `json:"status"`
	PublishedAt *string `json:"publishedAt,omitempty"`
}

type Post struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Slug        string  `json:"slug"`
	Excerpt     *string `json:"excerpt,omitempty"`
	Status      string  `json:"status"`
	PublishedAt *string `json:"publishedAt,omitempty"`
}

type PostConnection struct {
	Posts []*Post `json:"posts"`
}

type Query struct {
}

type RefreshInput struct {
	RefreshToken *string `json:"refreshToken,omitempty"`
}

type RegisterInput struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
	Password  string `json:"password"`
}

type Tag struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

type UpdateCategoryInput struct {
	ID   string  `json:"id"`
	Name *string `json:"name,omitempty"`
	Slug *string `json:"slug,omitempty"`
}

type UpdateTagInput struct {
	ID   string  `json:"id"`
	Name *string `json:"name,omitempty"`
	Slug *string `json:"slug,omitempty"`
}
