// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Page struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Slug        string  `json:"slug"`
	Status      string  `json:"status"`
	PublishedAt *string `json:"publishedAt,omitempty"`
}

type Post struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Slug        string  `json:"slug"`
	Excerpt     *string `json:"excerpt,omitempty"`
	Status      string  `json:"status"`
	PublishedAt *string `json:"publishedAt,omitempty"`
}

type PostConnection struct {
	Posts []*Post `json:"posts"`
}

type Query struct {
}
