package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"errors"
	"strings"

	"github.com/nextpresskit/backend/internal/graphql/generated"
	"github.com/nextpresskit/backend/internal/graphql/model"
	authApp "github.com/nextpresskit/backend/internal/modules/auth/application"
	pagesApp "github.com/nextpresskit/backend/internal/modules/pages/application"
	postApp "github.com/nextpresskit/backend/internal/modules/posts/application"
	taxApp "github.com/nextpresskit/backend/internal/modules/taxonomy/application"
	"github.com/nextpresskit/backend/internal/platform/jwtcookie"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthUser, error) {
	if r.Auth == nil {
		return nil, errors.New("auth_disabled")
	}
	if strings.TrimSpace(input.FirstName) == "" || strings.TrimSpace(input.LastName) == "" ||
		strings.TrimSpace(input.Email) == "" || strings.TrimSpace(input.Password) == "" {
		return nil, errors.New("invalid_payload")
	}
	u, err := r.Auth.Register(ctx, input.FirstName, input.LastName, input.Email, input.Password)
	if err != nil {
		return nil, err
	}
	return domainAuthUserToGQL(u), nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthTokens, error) {
	if r.Auth == nil {
		return nil, errors.New("auth_disabled")
	}
	if strings.TrimSpace(input.Email) == "" || strings.TrimSpace(input.Password) == "" {
		return nil, errors.New("invalid_payload")
	}
	u, access, refresh, err := r.Auth.Login(ctx, input.Email, input.Password)
	if err != nil {
		if errors.Is(err, authApp.ErrInvalidLogin) {
			return nil, errors.New("invalid_credentials")
		}
		return nil, err
	}

	if strings.EqualFold(r.JWT.AuthSource, "cookie") {
		if ginCtx, ok := GinContextFrom(ctx); ok {
			jwtcookie.SetAuthCookies(ginCtx.Writer, access, refresh, r.JWT)
		}
		return &model.AuthTokens{
			AccessToken:  nil,
			RefreshToken: nil,
			User:         domainAuthUserToGQL(u),
		}, nil
	}

	accessCopy := access
	refreshCopy := refresh
	return &model.AuthTokens{
		AccessToken:  &accessCopy,
		RefreshToken: &refreshCopy,
		User:         domainAuthUserToGQL(u),
	}, nil
}

// Refresh is the resolver for the refresh field.
func (r *mutationResolver) Refresh(ctx context.Context, input model.RefreshInput) (*model.AuthTokens, error) {
	if r.Auth == nil {
		return nil, errors.New("auth_disabled")
	}
	// In cookie mode, we read refresh token from HttpOnly cookies.
	if strings.EqualFold(r.JWT.AuthSource, "cookie") {
		if ginCtx, ok := GinContextFrom(ctx); ok {
			if v, ok := jwtcookie.GetCookieValue(ginCtx.Request, r.JWT.RefreshCookieName); ok {
				u, access, refresh, err := r.Auth.Refresh(ctx, v)
				if err != nil {
					if errors.Is(err, authApp.ErrInvalidLogin) {
						return nil, errors.New("invalid_refresh_token")
					}
					return nil, err
				}
				jwtcookie.SetAuthCookies(ginCtx.Writer, access, refresh, r.JWT)
				return &model.AuthTokens{
					AccessToken:  nil,
					RefreshToken: nil,
					User:         domainAuthUserToGQL(u),
				}, nil
			}
		}
		return nil, errors.New("invalid_refresh_token")
	}

	refreshToken := strings.TrimSpace("")
	if input.RefreshToken != nil {
		refreshToken = strings.TrimSpace(*input.RefreshToken)
	}
	if refreshToken == "" {
		return nil, errors.New("invalid_payload")
	}

	u, access, refresh, err := r.Auth.Refresh(ctx, refreshToken)
	if err != nil {
		if errors.Is(err, authApp.ErrInvalidLogin) {
			return nil, errors.New("invalid_refresh_token")
		}
		return nil, err
	}
	accessCopy := access
	refreshCopy := refresh
	return &model.AuthTokens{
		AccessToken:  &accessCopy,
		RefreshToken: &refreshCopy,
		User:         domainAuthUserToGQL(u),
	}, nil
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input model.CreateCategoryInput) (*model.Category, error) {
	if r.Taxonomy == nil {
		return nil, errors.New("taxonomy_disabled")
	}
	out, err := r.Taxonomy.CreateCategory(ctx, input.Name, input.Slug)
	if err != nil {
		return nil, err
	}
	return domainCategoryToGQL(out), nil
}

// UpdateCategory is the resolver for the updateCategory field.
func (r *mutationResolver) UpdateCategory(ctx context.Context, input model.UpdateCategoryInput) (*model.Category, error) {
	if r.Taxonomy == nil {
		return nil, errors.New("taxonomy_disabled")
	}
	out, err := r.Taxonomy.UpdateCategory(ctx, input.ID, valueOrEmpty(input.Name), valueOrEmpty(input.Slug))
	if err != nil {
		return nil, err
	}
	return domainCategoryToGQL(out), nil
}

// DeleteCategory is the resolver for the deleteCategory field.
func (r *mutationResolver) DeleteCategory(ctx context.Context, id string) (bool, error) {
	if r.Taxonomy == nil {
		return false, errors.New("taxonomy_disabled")
	}
	if err := r.Taxonomy.DeleteCategory(ctx, id); err != nil {
		if errors.Is(err, taxApp.ErrNotFound) {
			return false, nil
		}
		return false, err
	}
	return true, nil
}

// CreateTag is the resolver for the createTag field.
func (r *mutationResolver) CreateTag(ctx context.Context, input model.CreateTagInput) (*model.Tag, error) {
	if r.Taxonomy == nil {
		return nil, errors.New("taxonomy_disabled")
	}
	out, err := r.Taxonomy.CreateTag(ctx, input.Name, input.Slug)
	if err != nil {
		return nil, err
	}
	return domainTagToGQL(out), nil
}

// UpdateTag is the resolver for the updateTag field.
func (r *mutationResolver) UpdateTag(ctx context.Context, input model.UpdateTagInput) (*model.Tag, error) {
	if r.Taxonomy == nil {
		return nil, errors.New("taxonomy_disabled")
	}
	out, err := r.Taxonomy.UpdateTag(ctx, input.ID, valueOrEmpty(input.Name), valueOrEmpty(input.Slug))
	if err != nil {
		return nil, err
	}
	return domainTagToGQL(out), nil
}

// DeleteTag is the resolver for the deleteTag field.
func (r *mutationResolver) DeleteTag(ctx context.Context, id string) (bool, error) {
	if r.Taxonomy == nil {
		return false, errors.New("taxonomy_disabled")
	}
	if err := r.Taxonomy.DeleteTag(ctx, id); err != nil {
		if errors.Is(err, taxApp.ErrNotFound) {
			return false, nil
		}
		return false, err
	}
	return true, nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, slug string) (*model.Post, error) {
	if r.PostsCore == nil {
		return nil, nil
	}
	p, err := r.PostsCore.PublicGetBySlug(ctx, slug)
	if err != nil {
		if errors.Is(err, postApp.ErrPostNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return domainPostToGQL(p), nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, limit *int, offset *int) (*model.PostConnection, error) {
	if r.PostsCore == nil {
		return &model.PostConnection{Posts: []*model.Post{}}, nil
	}
	lim := 0
	if limit != nil {
		lim = *limit
	}
	off := 0
	if offset != nil {
		off = *offset
	}
	list, err := r.PostsCore.PublicList(ctx, lim, off, "", "", "")
	if err != nil {
		return nil, err
	}
	out := make([]*model.Post, 0, len(list))
	for i := range list {
		out = append(out, domainPostToGQL(&list[i]))
	}
	return &model.PostConnection{Posts: out}, nil
}

// SearchPosts is the resolver for the searchPosts field.
func (r *queryResolver) SearchPosts(ctx context.Context, q string, limit *int, offset *int) (*model.PostConnection, error) {
	if r.PostsCore == nil {
		return &model.PostConnection{Posts: []*model.Post{}}, nil
	}
	if r.Search == nil {
		return &model.PostConnection{Posts: []*model.Post{}}, nil
	}

	lim := 0
	if limit != nil {
		lim = *limit
	}
	off := 0
	if offset != nil {
		off = *offset
	}
	ids, err := r.Search.SearchPostIDs(ctx, q, lim, off)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Post, 0, len(ids))
	for _, id := range ids {
		p, err := r.PostsCore.GetByID(ctx, id)
		if err != nil || p == nil {
			continue
		}
		out = append(out, domainPostToGQL(p))
	}
	return &model.PostConnection{Posts: out}, nil
}

// Page is the resolver for the page field.
func (r *queryResolver) Page(ctx context.Context, slug string) (*model.Page, error) {
	if r.Pages == nil {
		return nil, nil
	}
	p, err := r.Pages.PublicGetBySlug(ctx, slug)
	if err != nil {
		if errors.Is(err, pagesApp.ErrPageNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return domainPageToGQL(p), nil
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context, limit *int, offset *int) ([]*model.Category, error) {
	if r.Taxonomy == nil {
		return []*model.Category{}, nil
	}
	lim := 0
	if limit != nil {
		lim = *limit
	}
	off := 0
	if offset != nil {
		off = *offset
	}
	list, err := r.Taxonomy.ListCategories(ctx, lim, off)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Category, 0, len(list))
	for i := range list {
		out = append(out, domainCategoryToGQL(&list[i]))
	}
	return out, nil
}

// Tags is the resolver for the tags field.
func (r *queryResolver) Tags(ctx context.Context, limit *int, offset *int) ([]*model.Tag, error) {
	if r.Taxonomy == nil {
		return []*model.Tag{}, nil
	}
	lim := 0
	if limit != nil {
		lim = *limit
	}
	off := 0
	if offset != nil {
		off = *offset
	}
	list, err := r.Taxonomy.ListTags(ctx, lim, off)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Tag, 0, len(list))
	for i := range list {
		out = append(out, domainTagToGQL(&list[i]))
	}
	return out, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
